### ISSUE TITLE
TypeError configuration.getEnvData is not a function

### ISSUE THREAD

**Issue by benjaminh** [mviewer/mviewer#723]
## Environnement
Mviewer : 3.9.1
Debian 10
Firefox 108

Déploiement avec composition docker (et Nginx servant de reverse-proxy) :
```
version: '3'

services:
  mviewer:
    image: mviewer/mviewer:stable
    ports:
      - 8080:80
    volumes:
      - ./apps:/usr/share/nginx/html/apps
```

## Description

Lors de l'accès à l'application par défaut (mon application est décrite dans `default.xml`), l'application reste sur l'écran de chargement.
La console affiche l'erreur suivante :
```
Uncaught TypeError: configuration.getEnvData is not a function
    success http://localhost:8080/:618
    jQuery 7
    _complete http://localhost:8080/js/configuration.js:197
    jQuery 2
    _complete http://localhost:8080/js/configuration.js:194
    success http://localhost:8080/:656
    jQuery 7
    _getExtensions http://localhost:8080/js/configuration.js:124
    jQuery 6
    ajaxFunction http://localhost:8080/js/configuration.js:110
    ajaxFunction http://localhost:8080/js/configuration.js:106
    _getExtensions http://localhost:8080/js/configuration.js:121
    success http://localhost:8080/:658
    jQuery 6
    <anonymous> http://localhost:8080/:606
    jQuery 11

```
Le problème ne survient pas avec Chromium (v. 108).
Je précise (car je ne sais pas si c'est lié) : la config ci-dessus en local (sans Nginx) fonctionne, mais si je change les ports par 8081, j'obtiens le même comportement que décrit plus haut.
